services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    container_name: simple-blog-backend

  db:
    image: postgres:14
    env_file:
      - app/.env
    environment:
      POSTGRES_DB: simple-blog
    ports:
      - "5432:5432"
    container_name: simple-blog-db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: simple-blog-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
